=== dengerpu/xml/3.2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ENTER_NAME_OF_ROOT_ELEMENT_HERE EMPTY>
	<!ELEMENT library (books,records)+>
	<!ELEMENT books (book)*>
	<!ELEMENT book (#PCDATA)>
	<!ELEMENT records (item)*>
	<!ELEMENT item (data,preson)>
	<!ELEMENT data (#PCDATA)>
	<!ELEMENT preson (#PCDATA)>
	<!ATTLIST library xmlns:bk CDATA #REQUIRED xmlns:pn CDATA #REQUIRED>
	<!ATTLIST book bk:bookid CDATA #REQUIRED>
	<!ATTLIST preson pn:name CDATA #REQUIRED borrowed CDATA #IMPLIED>

=== dengerpu/xml/3.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--引入外部DTD文件-->
<!DOCTYPE library SYSTEM "3.2.dtd">
<library xmlns:bk="http://www.erpu.com/book" xmlns:pn="http://www.erpu.com/person">
	<books>
		<book bk:bookid="b-1-1">XML详解</book>
		<book bk:bookid="b-1-2">HTML详解</book>
		<book bk:bookid="b-1-2">css详解</book>
	</books>
	<records>
		<item>
				<data>2012-01-01</data>
				<preson pn:name="张三" borrowed="b-1-1 b-1-2" />
		</item>
		<item>
				<data>2020-01-01</data>
				<preson pn:name="李四" borrowed="b-1-1 b-1-3" />
		</item>
	</records>
</library>
