=== dengerpu/xml/4.2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="books"/>
				<xs:element ref="records"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--对books属性的约束，通过引用来对子元素book的约束-->
	<xs:element name="books">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="book"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--对records的约束-->
	<xs:element name="records">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="item"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--对item的约束-->
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="date" type="xs:date"/>
				<xs:element ref="person"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--对book的约束-->
	<xs:element name="book">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="bookid" type="bookIDtype"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!--对book属性的约束-->
	<xs:simpleType name="bookIDtype">
		<xs:restriction base="xs:string">
			<xs:pattern value="b-\d{1}-\d{1}"/>
		</xs:restriction>
	</xs:simpleType>
	<!--对person的约束-->
	<xs:element name="person" nillable="true">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string"/>
					<xs:attribute name="borrowed">
						<xs:simpleType>
							<xs:list itemType="bookIDtype"/>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dengerpu/xml/4.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="4.2.xsd">
	<books>
		<book bookid="b-1-1">XML详解</book>
		<book bookid="b-1-2">Servlet从入门到精通</book>
		<book bookid="b-1-3">JSP实例编程</book>
	</books>
	<records>
		<item>
			<date>2012-08-01</date>
			<person name="张三" borrowed="b-1-1 b-1-2"/>
		</item>
		<item>
			<date>2012-08-02</date>
			<person name="李四" borrowed="b-1-1 b-1-3"/>
		</item>
	</records>
</library>
